[package]
name = "tambo-core"
version = "0.1.0"
edition = "2024"

[features]
native = ["typst-as-lib/typst-kit-fonts", "typst-as-lib/typst-kit-embed-fonts"]
default = ["native"]
[dependencies]
typst = "0.15"
typst-as-lib = "0.16"
typst-pdf = "0.15"
serde_json = "1"
thiserror = "2"
lopdf = { version = "0.44", features = ["wasm_js"] }
