use crate::json::json_to_typst_literal;
use serde_json::Value;

pub fn sanitize_template_name(value: &str) -> String {
    value
        .trim()
        .to_lowercase()
        .replace(' ', "-")
        .replace('_', "-")
        .chars()
        .filter(|c| c.is_alphanumeric() || *c == '-')
        .collect()
}

pub fn generate_standalone_typ(template_source: &str, entry: &Value) -> String {
    let data_literal = json_to_typst_literal(entry);
    let mut out = String::new();
    out.push_str("// Generated by tambo\n");
    out.push_str(&format!("#let __tambo_data = {}\n\n", data_literal));
    let mut body = template_source.replace("#import sys: inputs", "// data embedded above");
    body = body.replace("inputs.data", "__tambo_data");
    out.push_str(&body);
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_sanitize_template_name_lowercase() {
        assert_eq!(sanitize_template_name("Section 1"), "section-1");
    }

    #[test]
    fn test_sanitize_template_name_underscore_to_hyphen() {
        assert_eq!(sanitize_template_name("my_section"), "my-section");
    }

    #[test]
    fn test_sanitize_template_name_strip_special_chars() {
        assert_eq!(
            sanitize_template_name("Section 1: Intro!"),
            "section-1-intro"
        );
    }

    #[test]
    fn test_sanitize_template_name_trim() {
        assert_eq!(sanitize_template_name("  Default  "), "default");
    }

    #[test]
    fn test_generate_standalone_typ_basic() {
        let entry = json!({"Titre": "Test", "Auteur": "Moi"});
        let template = "#import sys: inputs\n#let d = inputs.data\n#d.at(\"Titre\")\n";
        let result = generate_standalone_typ(template, &entry);
        assert!(result.starts_with("// Generated by tambo\n#let __tambo_data = "));
        assert!(result.contains("Titre: \"Test\""));
        assert!(result.contains("// data embedded above"));
        assert!(result.contains("#let d = __tambo_data"));
        assert!(!result.contains("inputs.data"));
    }

    #[test]
    fn test_generate_standalone_typ_no_import() {
        let entry = json!({"x": 1});
        let template = "#let x = 1\n";
        let result = generate_standalone_typ(template, &entry);
        assert!(result.contains("#let __tambo_data = "));
        assert!(result.contains("#let x = 1"));
    }
}
