use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use clap::Parser;
use serde_json::Value;
use typst::foundations::{Dict, IntoValue};
use typst_as_lib::TypstEngine;
use typst_as_lib::file_resolver::FileSystemResolver;
use typst_as_lib::typst_kit_options::TypstKitFontOptions;

#[derive(Parser)]
#[command(name = "tambo", about = "Generate PDFs from JSON data using Typst templates")]
struct Cli {
    /// Input JSON file (array of objects)
    #[arg(short, long)]
    input: PathBuf,

    /// Directory containing Typst templates (.typ files)
    #[arg(short, long, default_value = "templates")]
    templates: PathBuf,

    /// Output directory for generated PDFs
    #[arg(short, long, default_value = "output")]
    output: PathBuf,

    /// JSON field used to select the template (e.g. "groupe")
    #[arg(long, default_value = "groupe")]
    field: String,

    /// Root directory for resolving relative image paths (defaults to JSON file's parent)
    #[arg(long)]
    root: Option<PathBuf>,
}

fn escape_typst_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '$' => out.push_str("\\$"),
            '\n' => out.push_str("\\n"),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

fn json_to_typst_literal(val: &Value) -> String {
    match val {
        Value::Null => "none".to_string(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => {
            if let Some(i) = n.as_i64() {
                i.to_string()
            } else if let Some(f) = n.as_f64() {
                f.to_string()
            } else {
                "none".to_string()
            }
        }
        Value::String(s) => escape_typst_string(s),
        Value::Array(arr) => {
            let items: Vec<String> = arr.iter().map(json_to_typst_literal).collect();
            format!("({})", items.join(", "))
        }
        Value::Object(map) => {
            let mut fields = Vec::with_capacity(map.len());
            // Sort keys for deterministic output
            let mut keys: Vec<&String> = map.keys().collect();
            keys.sort();
            for k in keys {
                let v = json_to_typst_literal(&map[k]);
                if k.chars().all(|c| c.is_alphanumeric() || c == '_')
                    && !k.starts_with(|c: char| c.is_ascii_digit())
                {
                    fields.push(format!("{}: {}", k, v));
                } else {
                    fields.push(format!("\"{}\": {}", k, v));
                }
            }
            format!("({})", fields.join(", "))
        }
    }
}

fn generate_standalone_typ(template_source: &str, entry: &Value) -> String {
    let data_literal = json_to_typst_literal(entry);
    let mut out = String::new();
    out.push_str("// Generated by tambo\n");
    out.push_str(&format!("#let __tambo_data = {}\n\n", data_literal));
    // Replace #import sys: inputs with a comment
    let mut body = template_source.replace("#import sys: inputs", "// data embedded above");
    // Replace any remaining inputs.data with __tambo_data
    body = body.replace("inputs.data", "__tambo_data");
    out.push_str(&body);
    out
}

fn sanitize_template_name(value: &str) -> String {
    value
        .trim()
        .to_lowercase()
        .replace(' ', "-")
        .replace('_', "-")
        .chars()
        .filter(|c| c.is_alphanumeric() || *c == '-')
        .collect()
}

fn json_to_typst_value(val: &Value) -> typst::foundations::Value {
    match val {
        Value::Null => typst::foundations::Value::None,
        Value::Bool(b) => (*b).into_value(),
        Value::Number(n) => {
            if let Some(i) = n.as_i64() {
                i.into_value()
            } else if let Some(f) = n.as_f64() {
                f.into_value()
            } else {
                typst::foundations::Value::None
            }
        }
        Value::String(s) => s.as_str().into_value(),
        Value::Array(arr) => {
            let items: Vec<typst::foundations::Value> =
                arr.iter().map(json_to_typst_value).collect();
            items.into_value()
        }
        Value::Object(map) => {
            let mut dict = Dict::new();
            for (k, v) in map {
                dict.insert(k.as_str().into(), json_to_typst_value(v));
            }
            dict.into_value()
        }
    }
}

fn compile_entry(
    entry: &Value,
    template_source: &str,
    root: &Path,
) -> Result<Vec<u8>> {
    let mut inputs = Dict::new();
    inputs.insert("data".into(), json_to_typst_value(entry));

    let main_file_id = "main.typ";
    let sources: Vec<(&str, &str)> = vec![(main_file_id, template_source)];

    let engine = TypstEngine::builder()
        .with_static_source_file_resolver(sources)
        .add_file_resolver(FileSystemResolver::new(root.to_path_buf()))
        .search_fonts_with(TypstKitFontOptions::default())
        .build();

    let warned = engine.compile_with_input(main_file_id, inputs);

    if !warned.warnings.is_empty() {
        for w in &warned.warnings {
            eprintln!("  warning: {w:?}");
        }
    }

    let doc = warned.output.map_err(|e| anyhow::anyhow!("Typst compilation failed: {e:?}"))?;

    let pdf = typst_pdf::pdf(&doc, &Default::default())
        .map_err(|e| anyhow::anyhow!("PDF export failed: {e:?}"))?;

    Ok(pdf)
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    if !cli.input.exists() {
        bail!("Input file not found: {}", cli.input.display());
    }
    if !cli.templates.exists() {
        bail!("Templates directory not found: {}", cli.templates.display());
    }

    let raw = fs::read_to_string(&cli.input)
        .with_context(|| format!("Failed to read {}", cli.input.display()))?;
    let entries: Vec<Value> =
        serde_json::from_str(&raw).with_context(|| "JSON must be an array of objects")?;

    fs::create_dir_all(&cli.output)?;

    let root = cli
        .root
        .map(|p| fs::canonicalize(&p).unwrap_or(p))
        .unwrap_or_else(|| {
            cli.input
                .canonicalize()
                .ok()
                .and_then(|p| p.parent().map(|pp| pp.to_path_buf()))
                .unwrap_or_else(|| std::env::current_dir().unwrap_or_else(|_| PathBuf::from(".")))
        });

    let mut template_cache: HashMap<String, String> = HashMap::new();

    for (i, entry) in entries.iter().enumerate() {
        let template_name = match entry.get(&cli.field).and_then(|v| v.as_str()) {
            Some(name) => sanitize_template_name(name),
            None => {
                eprintln!(
                    "[{}/{}] SKIP: no `{}` field",
                    i + 1,
                    entries.len(),
                    cli.field,
                );
                continue;
            }
        };

        let template_source = match template_cache.get(&template_name) {
            Some(src) => src.clone(),
            None => {
                let path = cli.templates.join(format!("{template_name}.typ"));
                if !path.exists() {
                    eprintln!(
                        "[{}/{}] SKIP: template not found: {}",
                        i + 1,
                        entries.len(),
                        path.display()
                    );
                    continue;
                }
                let src = fs::read_to_string(&path)
                    .with_context(|| format!("Failed to read {}", path.display()))?;
                template_cache.insert(template_name.clone(), src.clone());
                src
            }
        };

        let pdf_name = match entry.get("DEXID").and_then(|v| v.as_str()) {
            Some(name) => name.to_string(),
            None => i.to_string(),
        };

        let pdf_path = cli.output.join(format!("{pdf_name}.pdf"));

        eprint!("[{}/{}] {} ... ", i + 1, entries.len(), pdf_path.display());

        match compile_entry(entry, &template_source, &root) {
            Ok(pdf_bytes) => {
                fs::write(&pdf_path, &pdf_bytes)?;
                let typ_path = pdf_path.with_extension("typ");
                let typ_source = generate_standalone_typ(&template_source, entry);
                fs::write(&typ_path, &typ_source)?;
                eprintln!("ok ({} bytes, typ)", pdf_bytes.len());
            }
            Err(e) => {
                eprintln!("FAILED: {e}");
            }
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_sanitize_template_name_lowercase() {
        assert_eq!(sanitize_template_name("Section 1"), "section-1");
    }

    #[test]
    fn test_sanitize_template_name_underscore_to_hyphen() {
        assert_eq!(sanitize_template_name("my_section"), "my-section");
    }

    #[test]
    fn test_sanitize_template_name_strip_special_chars() {
        assert_eq!(sanitize_template_name("Section 1: Intro!"), "section-1-intro");
    }

    #[test]
    fn test_sanitize_template_name_trim() {
        assert_eq!(sanitize_template_name("  Default  "), "default");
    }

    #[test]
    fn test_json_to_typst_value_string() {
        let v = json_to_typst_value(&json!("hello"));
        let s = format!("{:?}", v);
        assert!(s.contains("hello"), "got {s:?}");
    }

    #[test]
    fn test_json_to_typst_value_null() {
        let v = json_to_typst_value(&Value::Null);
        assert_eq!(format!("{:?}", v), "None");
    }

    #[test]
    fn test_json_to_typst_value_integer() {
        let v = json_to_typst_value(&json!(42));
        let s = format!("{:?}", v);
        assert!(s.contains("42"), "got {s:?}");
    }

    #[test]
    fn test_json_to_typst_value_bool() {
        let v = json_to_typst_value(&json!(true));
        let s = format!("{:?}", v);
        assert!(s.contains("true"), "got {s:?}");
    }

    #[test]
    fn test_json_to_typst_value_array() {
        let v = json_to_typst_value(&json!(["a", "b"]));
        let s = format!("{:?}", v);
        assert!(s.contains('a'), "got {s:?}");
    }

    #[test]
    fn test_json_to_typst_value_object() {
        let v = json_to_typst_value(&json!({"key": "val"}));
        let s = format!("{:?}", v);
        assert!(s.contains("val"), "got {s:?}");
    }

    #[test]
    fn test_generate_standalone_typ_basic() {
        let entry = json!({"Titre": "Test", "Auteur": "Moi"});
        let template = "#import sys: inputs\n#let d = inputs.data\n#d.at(\"Titre\")\n";
        let result = generate_standalone_typ(template, &entry);
        assert!(result.starts_with("// Generated by tambo\n#let __tambo_data = "));
        assert!(result.contains("Titre: \"Test\""));
        assert!(result.contains("// data embedded above"));
        assert!(result.contains("#let d = __tambo_data"));
        assert!(!result.contains("inputs.data"));
    }

    #[test]
    fn test_generate_standalone_typ_no_import() {
        let entry = json!({"x": 1});
        let template = "#let x = 1\n";
        let result = generate_standalone_typ(template, &entry);
        assert!(result.contains("#let __tambo_data = "));
        assert!(result.contains("#let x = 1"));
    }

    #[test]
    fn test_json_to_typst_literal_string() {
        assert_eq!(json_to_typst_literal(&json!("hello")), r#""hello""#);
    }

    #[test]
    fn test_json_to_typst_literal_null() {
        assert_eq!(json_to_typst_literal(&Value::Null), "none");
    }

    #[test]
    fn test_json_to_typst_literal_integer() {
        assert_eq!(json_to_typst_literal(&json!(42)), "42");
    }

    #[test]
    fn test_json_to_typst_literal_bool() {
        assert_eq!(json_to_typst_literal(&json!(true)), "true");
    }

    #[test]
    fn test_json_to_typst_literal_array() {
        assert_eq!(json_to_typst_literal(&json!(["a", "b"])), r#"("a", "b")"#);
    }

    #[test]
    fn test_json_to_typst_literal_object() {
        let result = json_to_typst_literal(&json!({"key": "val"}));
        assert_eq!(result, r#"(key: "val")"#);
    }

    #[test]
    fn test_escape_typst_string_basic() {
        assert_eq!(escape_typst_string("hello"), r#""hello""#);
    }

    #[test]
    fn test_escape_typst_string_special_chars() {
        assert_eq!(escape_typst_string("say \"hi\" $5"), r#""say \"hi\" \$5""#);
    }

    #[test]
    fn test_compile_entry_minimal() {
        let entry = json!({
            "Titre": "Test",
            "Auteur": "Test",
            "Date": "2024",
            "explicatif": null,
            "Credit line": "CC0",
            "traduction": null,
            "Pays": "France",
            "Ville": "Paris",
            "Domaine": "Test",
            "Designation rédigee": "test",
            "Prêteur": "Test",
            "N° inventaire prêteur": "T-01",
            "DEXID": "01",
            "Image ref": null,
        });

        let template = r#"
#import sys: inputs
#let d = inputs.data
#d.at("Titre")
"#;

        let result = compile_entry(&entry, template, Path::new("."));
        assert!(result.is_ok(), "compilation should succeed: {:?}", result.err());
        let pdf = result.unwrap();
        assert!(!pdf.is_empty(), "PDF should not be empty");
        assert!(pdf.starts_with(b"%PDF-"), "should start with PDF magic bytes");
    }
}
